### ISSUE TITLE
not enough values to unpack (expected 7, got 0)

### ISSUE THREAD

**Issue by ZhaoNan1** [yanwei-li/PanopticFCN#34]
Hi,
    Thank you very much for your contribution!
    I encountered the following problem when using the code to train on the cityscapes dataset

Traceback (most recent call last):
  File "/home/zhaonan/anaconda3/envs/detectron2/lib/python3.9/site-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/zhaonan/anaconda3/envs/detectron2/lib/python3.9/site-packages/detectron2/engine/defaults.py", line 497, in run_step
    self._trainer.run_step()
  File "/home/zhaonan/anaconda3/envs/detectron2/lib/python3.9/site-packages/detectron2/engine/train_loop.py", line 273, in run_step
    loss_dict = self.model(data)
  File "/home/zhaonan/anaconda3/envs/detectron2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhaonan/panoptic_segmentation/PanopticFCN/panopticfcn/panoptic_seg.py", line 112, in forward
    return self.losses(pred_centers, pred_regions, pred_weights, encode_feat, gt_dict)
  File "/home/zhaonan/panoptic_segmentation/PanopticFCN/panopticfcn/panoptic_seg.py", line 156, in losses
    loss_pos_ths, loss_pos_sts, idx_feat_th, weighted_values, idx_feat_st, thing_nums, stuff_nums = \
ValueError: not enough values to unpack (expected 7, got 0)

**Comment by ZhaoNan1** [comment]
I have solved it！

**Comment by 41-jjyy** [comment]
> I have solved it！

 I encountered the same problem.How to solve it?please
