### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by kuozhijishou** [yanwei-li/PanopticFCN#39]
按照指引做的cityspaces数据集
运行过程中发现：batched_input 中没有 "instances"键值，导致报错
请问是我哪里做错了吗

**Comment by kuozhijishou** [comment]
Traceback (most recent call last):
  File "/data/share/liwqg/workpath/code/python/segmentation/detectron2/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/data/share/liwqg/workpath/code/python/segmentation/detectron2/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/data/share/liwqg/workpath/code/python/segmentation/detectron2/detectron2/engine/train_loop.py", line 273, in run_step
    loss_dict = self.model(data)
  File "/home/liwqg/miniconda3/envs/torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/liwqg/workpath/code/python/segmentation/detectron2/projects/PanopticFCN/panopticfcn/panoptic_seg.py", line 99, in forward
    return self.losses(pred_centers, pred_regions, pred_weights, encode_feat, gt_dict)
  File "/home/liwqg/workpath/code/python/segmentation/detectron2/projects/PanopticFCN/panopticfcn/panoptic_seg.py", line 142, in losses
    loss_pos_ths, loss_pos_sts, idx_feat_th, weighted_values, idx_feat_st, thing_nums, stuff_nums = \
ValueError: not enough values to unpack (expected 7, got 0)

**Comment by yanwei-li** [comment]
Hi, the cityscapes dataset should be first processed for training. Maybe the [third-party](https://github.com/DdeGeus/PanopticFCN_cityscapes/blob/main/data/cityscapes/cityscapes_panoptic_separated.py) implementation on Cityscapes could help you.
